version: '3'
services:
  shell:
    build: 
      context: ./shell
      dockerfile: Dockerfile
      args:
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: pass
    image: alpine/mongosh
   
    environment:
      MONGO_INITDB_ROOT_USERNAME: user 
      MONGO_INITDB_ROOT_PASSWORD: pass 
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mongoDbTp


  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - mongoDbTp
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

networks:
  mongoDbTp:
    driver: bridge